force-app/main/default/objects/Case/fields/ClickUp_Task_Id__c.field-meta.xml
<CustomField>
    <fullName>ClickUp_Task_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ClickUp Task Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClickUp__c/ClickUp__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ClickUp1</label>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/ClickUp_Folder_Id__c.field-meta.xml
<CustomField>
    <fullName>ClickUp_Folder_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ClickUp Folder Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Timecard__c/Timecard__c.object-meta.xml
<CustomObject>
    <label>Timecard</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Timecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timecard__c/fields/ClickUp_Time_Id__c.field-meta.xml
<CustomField>
    <fullName>ClickUp_Time_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ClickUp Time Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Case__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClickUpSelector.cls
/**
 * Created by artsiomartsiomenka on 19/03/2024.
 */

public without sharing class ClickUpSelector {
    public static Contact getContactByEmail(String email) {
        return (Contact) new pp_Query('Contact')
                .selectAllFields()
                .addConditionNotNull('Email')
                .addCondition(
                        pp_Query.doAnd(
                                pp_Query.conditionEq(Contact.Email, email),
                                pp_Query.conditionEq(Contact.Inactive__c, false)
                        )
                )
                .fetch();
    }

    public static Map<String, SObject> getContactsByEmailMap(Set<String> emailSet) {
        Map<String, SObject> contactMap = new Map<String, SObject>();
        List<Contact> contacts = new List<Contact>();
        contacts = new pp_Query('Contact')
                .selectAllFields()
                .addConditionNotNull('Email')
                .addCondition(
                        pp_Query.doAnd(
                                pp_Query.conditionIn(Contact.Email, emailSet),
                                pp_Query.conditionEq(Contact.Inactive__c, false)
                        )
                )
                .run();

        if (contacts.isEmpty()) return contactMap;

        return (Map<String, SObject>) pp_R.of(contacts)
                .indexBy(pp_R.prop.apply('Email'))
                .toSObjectMap();
    }

    public static Case getCaseByClickUpTaskId(String clickUpTaskId) {
        return (Case) new pp_Query('Case')
                .selectAllFields()
                .selectFields('Contact.Email, Project__r.ClickUp_Folder_Id__c')
                .addConditionEq(Case.ClickUp_Task_Id__c, clickUpTaskId)
                .fetch();
    }

    public static Case getCaseById(String caseId) {
        return (Case) new pp_Query('Case')
                .selectAllFields()
                .selectFields('Contact.Email, Project__r.ClickUp_Folder_Id__c')
                .addConditionEq(Case.Id, caseId)
                .fetch();
    }

    public static Project__c getProjectByClickUpId(String projectId, String listId) {
        return (Project__c) new pp_Query('Project__c')
                .selectAllFields()
                .addConditionNotNull(Project__c.ClickUp_Folder_Id__c)
                .addCondition(
                    pp_Query.doOr(
                            pp_Query.conditionEq(Project__c.ClickUp_Folder_Id__c, projectId),
                            pp_Query.conditionEq(Project__c.ClickUp_Folder_Id__c, listId),
                            pp_Query.conditionLike(Project__c.ClickUp_Folder_Id__c, '%' + projectId + '%'),
                            pp_Query.conditionLike(Project__c.ClickUp_Folder_Id__c, '%' + listId + '%')
                    )
                )
                .fetch();
    }

    public static Timecard__c getTimeCardByIntervalId(String intervalId) {
        return (Timecard__c) new pp_Query('Timecard__c')
                .selectAllFields()
                .addConditionNotNull(Timecard__c.ClickUp_Time_Id__c)
                .addConditionEq(Timecard__c.ClickUp_Time_Id__c, intervalId)
                .fetch();
    }

    public static Map<String, SObject> getTimeCardsByClickUpId(Set<String> clickUpIds) {
        Map<String, Timecard__c> timeCardMap = new Map<String, Timecard__c>();
        List<Timecard__c> timeCards = new List<Timecard__c>();
        timeCards = new pp_Query('Timecard__c')
                .selectAllFields()
                .addConditionNotNull(Timecard__c.ClickUp_Time_Id__c)
                .addConditionEq(Timecard__c.ClickUp_Time_Id__c, clickUpIds)
                .run();

        if (timeCards.isEmpty()) return timeCardMap;

        return (Map<String, SObject>) pp_R.of(timeCards)
                .indexBy(pp_R.prop.apply('ClickUp_Time_Id__c'))
                .toSObjectMap();
    }

    public static String getClickUpTaskById(String taskId) {
        String resStr = new pp_RestExplorer(ClickUp__c.getOrgDefaults().Endpoint__c + 'task/'+taskId)
                .doGet()
                .setHeader('Authorization', ClickUp__c.getOrgDefaults().API_Key__c)
                .getResult();

        return resStr;
    }
}