force-app/main/default/objects/Case/fields/Internal_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Internal_System_ID__c</fullName>
    <label>Internal System ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Key__c.field-meta.xml
<CustomField>
    <fullName>Project_Key__c</fullName>
    <label>Project Key</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ProjectTrigger.cls
/**
 * Created on 03/01/2023.
 */

public with sharing class ProjectTrigger extends pp_Trap.TriggerHandler {
    public override void setUpAfterUpdate(pp_Trap.BulkObject bulkObj) {
        bulkObj.newStream
                .tap(pp_R.debug.apply('after update'))
                .tap(bulkObj.data('projectIds', pp_R.toIdSet.apply(new Set<Id>())))
                .filter((pp_Func)pp_R.allPass.run(
                        pp_R.propSatisfies.apply('Project_Key__c', pp_R.isNotEmpty),
                        pp_Trap.F.changed.apply('Project_Key__c')
                ))
                .subscribe(bulkObj.provide('projectIds', new CollectProjectIdsFunc()), null, bulkObj.provide('projectIds', new UpdateCasesFunc()));
    }



    class CollectProjectIdsFunc extends pp_Func {
        public CollectProjectIdsFunc() {
            super(2);
        }

        public override Object exec(Object arg1, Object arg2) {
            Set<Id> projectIds = (Set<Id>)arg1;
            projectIds.add(((Project__c)arg2).Id);
            return projectIds;
        }
    }
    class UpdateCasesFunc extends pp_Func {
        public UpdateCasesFunc() {
            super(1);
        }

        public override Object exec(Object arg) {
            Set<Id> projectIds = (Set<Id>)arg;
            pp_Trap.getInstance().disable('Project__c');
            update new pp_Query('Case')
                    .addConditionIn('Project__c', projectIds)
                    .addConditionNull('Internal_System_ID__c')
                    .orderBy('CreatedDate', 'ASC')
                    .setLimit(10000)
                    .run();
            pp_Trap.getInstance().enable('Project__c');
            return null;
        }
    }
}