force-app/main/default/objects/Case/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Time_Spent_This_Month__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent_This_Month__c</fullName>
    <label>Time Spent This Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TimeSpentThisMonthBatch.cls
global class TimeSpentThisMonthBatch implements Database.Batchable<sObject> {

	public String query;

	global TimeSpentThisMonthBatch(){
		this.query = 'SELECT Time_Spent_This_Month__c, Project__c, Project__r.Time_Spent_This_Month__c FROM Case ' +
				'WHERE Time_Spent_This_Month__c != null AND Time_Spent_This_Month__c > 0';
	}

	global System.Iterable<sObject> start(Database.BatchableContext jobId) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext jobId, List<sObject> recordList) {
		Set<Id> projectIds = new Set<Id>();
		for(Case caseObject: (List<Case>)recordList){
			caseObject.Time_Spent_This_Month__c = 0;
			if(caseObject.Project__r.Time_Spent_This_Month__c != null
					&& caseObject.Project__r.Time_Spent_This_Month__c > 0) projectIds.add(caseObject.Project__c);
		}
		Database.update(recordList, false);
		if(!projectIds.isEmpty()) updateRelatedProjects(projectIds);
	}

	private static void updateRelatedProjects(Set<Id> projectIds){
		List<Project__c> projects = new pp_Query('Project__c').selectAllFields().byId(projectIds).run();
		for(Project__c project: projects){
			project.Time_Spent_This_Month__c = 0;
		}
		Database.update(projects);
	}

	global void finish(Database.BatchableContext jobId) {}
}