force-app/main/default/objects/Case/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Time_Spent__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent__c</fullName>
    <label>Time Spent</label>
    <summarizedField>Timecard__c.Effort__c</summarizedField>
    <summaryForeignKey>Timecard__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Case/fields/Time_Spent_This_Month__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent_This_Month__c</fullName>
    <label>Time Spent This Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Timecard__c/Timecard__c.object-meta.xml
<CustomObject>
    <label>Timecard</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Timecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timecard__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Effort__c.field-meta.xml
<CustomField>
    <fullName>Effort__c</fullName>
    <label>Effort</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Case__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseTest.cls
@IsTest
private class CaseTest {

    @TestSetup
    public static void setup(){
        Account acc = new Account(Name = 'TestAccount');
        insert acc;
        Project__c project1 = new Project__c(Name = 'Test Project1', Account__c = acc.Id);
        Project__c project2 = new Project__c(Name = 'Test Project2', Account__c = acc.Id);
        insert new List<Project__c>{project1, project2};
        Case case1_p1 = new Case(Subject = 'Case1_p1', Project__c = project1.Id);
        Case case2_p1 = new Case(Subject = 'Case2_p1', Project__c = project1.Id);
        Case case1_p2 = new Case(Subject = 'Case1_p2', Project__c = project2.Id);
        Case case2_p2 = new Case(Subject = 'Case2_p2', Project__c = project2.Id);
        insert new List<Case>{case1_p1, case2_p1, case1_p2, case2_p2};
        Date lastMonth = Date.today().addMonths(-1);
        Timecard__c card1_lastMonth = new Timecard__c(Case__c = case1_p1.Id, Effort__c = 13, Work_Date__c = lastMonth);
        Timecard__c card2_lastMonth = new Timecard__c(Case__c = case1_p2.Id, Effort__c = 17, Work_Date__c = lastMonth);
        insert new List<Timecard__c>{card1_lastMonth, card2_lastMonth};
    }

    @IsTest
    private static void updateTest(){
        List<Case> casesToUpdate = new List<Case>();
        List<Case> p1_cases = new pp_Query('Case').addConditionEq('Project__r.Name', 'Test Project1').run();
        List<Case> p2_cases = new pp_Query('Case').addConditionEq('Project__r.Name', 'Test Project2').run();
        for (Case p1case: p1_cases){
            p1case.Time_Spent_This_Month__c = 12;
        }
        for (Case p2case: p2_cases){
            p2case.Time_Spent_This_Month__c = 3;
        }
        casesToUpdate.addAll(p1_cases);
        casesToUpdate.addAll(p2_cases);
        Test.startTest();
        update casesToUpdate;
        Test.stopTest();
        Project__c project1 = (Project__c)new pp_Query('Project__c')
                .selectFields(new Set<String>{'Time_Spent__c', 'Time_Spent_This_Month__c'})
                .addConditionEq('Name', 'Test Project1')
                .fetch();
        Project__c project2 = (Project__c)new pp_Query('Project__c')
                .selectFields(new Set<String>{'Time_Spent__c', 'Time_Spent_This_Month__c'})
                .addConditionEq('Name', 'Test Project2')
                .fetch();
        pp_T.expect(project1.Time_Spent__c).toEqual(13);
        pp_T.expect(project1.Time_Spent_This_Month__c).toEqual(24);
        pp_T.expect(project2.Time_Spent__c).toEqual(17);
        pp_T.expect(project2.Time_Spent_This_Month__c).toEqual(6);
    }

    @IsTest
    private static void deleteTest(){
        Test.startTest();
        delete [SELECT Id FROM Timecard__c];
        delete [SELECT Id FROM Case];
        Test.stopTest();
        List<Project__c> projects = new pp_Query('Project__c')
                .selectFields(new Set<String>{'Time_Spent__c', 'Time_Spent_This_Month__c'})
                .run();
        for (Project__c project: projects){
            pp_T.expect(project.Time_Spent__c).toEqual(0);
            pp_T.expect(project.Time_Spent_This_Month__c).toEqual(0);
        }
    }
}