force-app/main/default/objects/Vacation__c/Vacation__c.object-meta.xml
<CustomObject>
    <label>Vacation</label>
    <nameField>
        <displayFormat>VAC-{000000}</displayFormat>
        <label>Vacation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Past</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Vacation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Vacation_End_Date__c</fullName>
    <label>Vacation End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Vacation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Start_Date__c</fullName>
    <label>Vacation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PastVacationTest.cls
@isTest
private class PastVacationTest {
    static testMethod void pastVacationTest() {
        Test.startTest();

        Vacation__c vac = new Vacation__c(
        	Status__c = 'Confirmed',
        	Vacation_Start_Date__c = Date.today().addDays(-5),
        	Vacation_End_Date__c = Date.today().addDays(-2)
        );
        insert vac;

        PastVacationScheduler s = new PastVacationScheduler();
		s.execute(null);

        Test.stopTest();

        Vacation__c updateVac = (Vacation__c) new pp_Query('Vacation__c').selectField('Status__c').byId(vac.Id).fetch();
        System.assertEquals('Past', updateVac.Status__c);
    }
}