force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Planned_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_Time__c</fullName>
    <label>Planned Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <label>Estimated Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacation__c/Vacation__c.object-meta.xml
<CustomObject>
    <label>Vacation</label>
    <nameField>
        <displayFormat>VAC-{000000}</displayFormat>
        <label>Vacation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vacations</relationshipLabel>
    <relationshipName>Vacations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Vacation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Vacation_End_Date__c</fullName>
    <label>Vacation End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Vacation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Start_Date__c</fullName>
    <label>Vacation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Vacation_Type__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Type__c</fullName>
    <label>Vacation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day Off</fullName>
                <default>true</default>
                <label>Day Off</label>
            </value>
            <value>
                <fullName>Holiday Season</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>Personal Vacation</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResourceUtilizationController.cls
/**
 * Created on 17/03/2023.
 */

public with sharing class ResourceUtilizationController {
    @AuraEnabled
    public static Map<String, Object> getResourcesWithAssignments(Date dateFrom, Date dateTo) {
        List<Contact> resources = getActiveInternalContacts();
        Set<Id> contactIds = new Map<Id, Contact>(resources).keySet();
        return new Map<String, Object>{
                'resources' => resources,
                'cases' => getCasesForRange(contactIds, new pp_Moment().toDate(), dateTo),
                'bookings' => getBookings(contactIds, dateFrom, dateTo),
                'vacations' => getVacations(contactIds, dateFrom, dateTo)
        };
    }

    private static List<Contact> getActiveInternalContacts() {
        return new pp_Query('Contact')
                .selectFields(new Set<String>{'Id', 'Name'})
                .addConditionEq('Inactive__c', false)
                .addConditionEq('Account.Name', 'Propeller Plan')
                .orderBy('Name')
                .run();
    }
    private static List<Case> getCasesForRange(Set<Id> contactIds, Date dateFrom, Date dateTo) {
        return new pp_Query('Case')
                .selectFields(new Set<String>{'Id', 'Subject', 'Project__c', 'Project__r.Name', 'Start_Date__c', 'Due_Date__c', 'ContactId', 'Estimated_Time__c'})
                .addConditionIn('ContactId', contactIds)
                .addConditionGt('Estimated_Time__c', 0)
                .addCondition(pp_Query.doOr(
                        pp_Query.doAnd(
                                pp_Query.conditionNull('Start_Date__c'),
                                pp_Query.conditionLe('Due_Date__c', dateTo),
                                pp_Query.conditionGe('Due_Date__c', dateFrom)
                        ),
                        pp_Query.doAnd(
                                pp_Query.conditionLe('Start_Date__c', dateTo),
                                pp_Query.conditionGe('Due_Date__c', dateFrom)
                        )
                ))
                .orderBy('Start_Date__c')
                .orderBy('Due_Date__c')
                .orderBy('Subject')
                .run();
    }
    private static List<Case> getBookings(Set<Id> contactIds, Date dateFrom, Date dateTo) {
        return new pp_Query('Booking__c')
                .selectFields(new Set<String>{'Id', 'Name', 'Project__c', 'Project__r.Name', 'Start_Date__c', 'End_Date__c', 'Contact__c', 'Planned_Time__c'})
                .addConditionIn('Contact__c', contactIds)
                .addConditionLe('Start_Date__c', dateTo)
                .addConditionGe('End_Date__c', dateFrom)
                .orderBy('Start_Date__c')
                .orderBy('End_Date__c')
                .orderBy('Name')
                .run();
    }
    private static List<Case> getVacations(Set<Id> contactIds, Date dateFrom, Date dateTo) {
        return new pp_Query('Vacation__c')
                .selectFields(new Set<String>{'Id', 'Vacation_Type__c', 'Vacation_Start_Date__c', 'Vacation_End_Date__c', 'Employee__c'})
                .addConditionIn('Employee__c', contactIds)
                .addConditionLe('Vacation_Start_Date__c', dateTo)
                .addConditionGe('Vacation_End_Date__c', dateFrom)
                .orderBy('Vacation_Start_Date__c')
                .orderBy('Vacation_End_Date__c')
                .run();
    }
}