force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used only for Propeller Plan account records</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Case/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <label>Estimated Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Time_Spent_This_Month__c.field-meta.xml
<CustomField>
    <fullName>Time_Spent_This_Month__c</fullName>
    <label>Time Spent This Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>PropellerPlan Team</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Commission_Rate__c</fullName>
    <description>UpWork / Sales Reps / other robbers</description>
    <label>Commission Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Timecard__c/Timecard__c.object-meta.xml
<CustomObject>
    <label>Timecard</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Timecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timecard__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Effort__c.field-meta.xml
<CustomField>
    <fullName>Effort__c</fullName>
    <label>Effort</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This contact is inactive.</errorMessage>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>Propeller Plan</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Case__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TimeSpentThisMonthTest.cls
@IsTest
private class TimeSpentThisMonthTest {

	@IsTest
	static void timeSpentThisMonthTest() {
		Id contactRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
		Test.startTest();
		Account account = new Account(Name = 'Propeller Plan');
		insert account;
		Project__c project = createProject(account.Id);
		insert project;
		Contact newContact = createContact(account.Id);
		newContact.RecordTypeId = contactRTId;
		insert newContact;
		Case newCase = createCase(newContact.Id, project.Id);
		insert newCase;
		Timecard__c timecard = new Timecard__c(
				Work_Date__c = Date.today(),
				Effort__c = 5.50,
				Case__c = newCase.Id,
				Person__c = newContact.Id,
				Description__c = 'Test Expense'
		);
		insert timecard;
		TimeSpentThisMonthResetScheduler sch = new TimeSpentThisMonthResetScheduler();
		sch.execute(null);
		Test.stopTest();
		List<Case> cases = new pp_Query('Case').selectField('Time_Spent_This_Month__c').byId(newCase.Id).run();
		System.assertEquals(0.00, cases[0].Time_Spent_This_Month__c);
	}

	static Contact createContact(Id accountId) {
		Contact contactVar = new Contact();
		contactVar.FirstName = 'TestFirstName';
		contactVar.LastName = 'TestLastName';
		contactVar.Email = 'TestFirstName_TestLastName' + System.now().getTime() + '@mailinator.com';
		contactVar.AccountId = accountId;
		return contactVar;
	}

	static Project__c createProject(Id accountId) {
		Project__c projectRecord = new Project__c();
		projectRecord.Name = 'Project';
		projectRecord.Account__c = accountId;
		projectRecord.Rate__c = 100;
		projectRecord.Commission_Rate__c = 1;
		return projectRecord;
	}

	static Case createCase(Id contactId, Id projectId) {
		Case caseRecord = new Case();
		caseRecord.Project__c = projectId;
		caseRecord.Subject = 'Subject';
		caseRecord.ContactId = contactId;
		caseRecord.Estimated_Time__c = 10;
		return caseRecord;
	}
}