force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used only for Propeller Plan account records</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Banks</relationshipLabel>
    <relationshipName>Banks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <summarizedField>Bank_Account__c.Balance__c</summarizedField>
    <summaryForeignKey>Bank_Account__c.Bank__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(deprecated)Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>PropellerPlan Team</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/PPRS_SObject_Setting__mdt/PPRS_SObject_Setting__mdt.object-meta.xml
<CustomObject>
    <label>PPRS SObject Setting</label>
    <pluralLabel>PPRS SObject Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/PPRS_SObject_Setting__mdt/fields/DynamoDB_Partition_Key__c.field-meta.xml
<CustomField>
    <fullName>DynamoDB_Partition_Key__c</fullName>
    <label>DynamoDB Partition Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPRS_SObject_Setting__mdt/fields/DynamoDB_Table_Name__c.field-meta.xml
<CustomField>
    <fullName>DynamoDB_Table_Name__c</fullName>
    <label>DynamoDB Table Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Income_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Income_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Income Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Income Transactions</relationshipLabel>
    <relationshipName>Income_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Outcome_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outcome Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Outcome Transactions</relationshipLabel>
    <relationshipName>Outcome_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TransactionTest.cls
/**
 * Created by yarikmeshcheryakov on 20.02.23.
 */

@IsTest
private class TransactionTest {
    static testMethod void transactionTest() {
        Account accountRecord = new Account(Name = 'Propeller Plan');
        accountRecord.RecordTypeId =
            Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        insert accountRecord;

        Contact testContact = new Contact(
            LastName = 'Last Name',
            Email = 'last.name@email.com',
            AccountId = accountRecord.Id
        );
        insert testContact;

        Bank__c bank = new Bank__c(
            Account__c = accountRecord.Id,
            Name = 'Test Bank'
        );
        insert bank;

        Bank_Account__c bankAccount = new Bank_Account__c(
            Name = 'Test Bank USD',
            Bank__c = bank.Id
        );
        insert bankAccount;

        PPRSSettings.settingsMdt.add(
            new PPRS_SObject_Setting__mdt(
                DeveloperName = 'Transaction__c',
                MasterLabel = 'Transaction__c',
                SObjectType__c = 'Transaction__c',
                DynamoDB_Table_Name__c = 'Transaction__c',
                DynamoDB_Partition_Key__c = 'partition_id'
            )
        );
        Transaction__c tr = new Transaction__c(
            Person__c = testContact.Id,
            Income__c = 100,
            Income_Bank_Account__c = bankAccount.Id,
            Description__c = 'TEST TEST',
            Date__c = Date.today()
        );
        insert tr;

        System.assertEquals(100, [SELECT Balance__c FROM Bank_Account__c WHERE Id =: bankAccount.Id].Balance__c);

        tr.Outcome__c = 50;
        tr.Outcome_Bank_Account__c = bankAccount.Id;
        update tr;
        System.assertEquals(50, [SELECT Balance__c FROM Bank_Account__c WHERE Id =: bankAccount.Id].Balance__c);

        delete tr;
        System.assertEquals(0, [SELECT Balance__c FROM Bank_Account__c WHERE Id =: bankAccount.Id].Balance__c);
    }
}