force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used only for Propeller Plan account records</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Banks</relationshipLabel>
    <relationshipName>Banks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Compensation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compensation__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Billing_Person__c.field-meta.xml
<CustomField>
    <fullName>Billing_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Compensations (Billing Person)</relationshipLabel>
    <relationshipName>Paid_Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Birthday</fullName>
            </value>
            <value>
                <fullName>Business Trip</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Legal and Accounting</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Salary</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Sport</fullName>
            </value>
            <value>
                <fullName>Tax</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(deprecated)Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>PropellerPlan Team</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Loan__c/Loan__c.object-meta.xml
<CustomObject>
    <label>Loan</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Billing_Person__c.field-meta.xml
<CustomField>
    <fullName>Billing_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans (Billing Person)</relationshipLabel>
    <relationshipName>Persons_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loans</relationshipLabel>
    <relationshipName>Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PPRS_SObject_Setting__mdt/PPRS_SObject_Setting__mdt.object-meta.xml
<CustomObject>
    <label>PPRS SObject Setting</label>
    <pluralLabel>PPRS SObject Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/PPRS_SObject_Setting__mdt/fields/DynamoDB_Partition_Key__c.field-meta.xml
<CustomField>
    <fullName>DynamoDB_Partition_Key__c</fullName>
    <label>DynamoDB Partition Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PPRS_SObject_Setting__mdt/fields/DynamoDB_Table_Name__c.field-meta.xml
<CustomField>
    <fullName>DynamoDB_Table_Name__c</fullName>
    <label>DynamoDB Table Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <formula>IF (
    AND (
								NOT(ISBLANK(Income__c)),
								NOT(ISBLANK(Outcome__c))
    ),
				&apos;Transfer&apos;,
				IF (
								NOT(ISBLANK(Income__c)),
								TEXT(Income_Category__c),  
								TEXT(Outcome_Category__c)
				)
)</formula>
    <label>Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Compensation__c.field-meta.xml
<CustomField>
    <fullName>Compensation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compensation</label>
    <referenceTo>Compensation__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Income_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Income_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Income Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Income Transactions</relationshipLabel>
    <relationshipName>Income_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Loan__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BackupPPRS_Test.cls
/**
 * Created by kirillreutski on 5.12.24.
 */

@IsTest
private class BackupPPRS_Test {
    @IsTest
    static void compensations() {

        PPRSSettings.settingsMdt.add(
                new PPRS_SObject_Setting__mdt(
                        DeveloperName = 'Transaction__c',
                        MasterLabel = 'Transaction__c',
                        SObjectType__c = 'Transaction__c',
                        DynamoDB_Table_Name__c = 'Transaction__c',
                        DynamoDB_Partition_Key__c = 'partition_id'
                )
        );
        PPRSSettings.settingsMdt.add(
                new PPRS_SObject_Setting__mdt(
                        DeveloperName = 'Compensation__c',
                        MasterLabel = 'Compensation__c',
                        SObjectType__c = 'Compensation__c',
                        DynamoDB_Table_Name__c = 'Compensation__c',
                        DynamoDB_Partition_Key__c = 'partition_id'
                )
        );
        PPRSSettings.settingsMdt.add(
                new PPRS_SObject_Setting__mdt(
                        DeveloperName = 'Loan__c',
                        MasterLabel = 'Loan__c',
                        SObjectType__c = 'Loan__c',
                        DynamoDB_Table_Name__c = 'Loan__c',
                        DynamoDB_Partition_Key__c = 'partition_id'
                )
        );


        Account accountRecord = new Account(Name = 'Propeller Plan');
        accountRecord.RecordTypeId =
                Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        insert accountRecord;

        Contact testContact = new Contact(
                LastName = 'Last Name',
                Email = 'last.name@email.com',
                AccountId = accountRecord.Id
        );
        insert testContact;

        Bank__c bank = new Bank__c(
                Account__c = accountRecord.Id,
                Name = 'Test Bank'
        );
        insert bank;

        Bank_Account__c bankAccount = new Bank_Account__c(
                Name = 'Test Bank USD',
                Bank__c = bank.Id
        );
        insert bankAccount;

        Transaction__c tr = new Transaction__c(
                Person__c = testContact.Id,
                Income__c = 100,
                Income_Bank_Account__c = bankAccount.Id,
                Description__c = 'TEST TEST',
                Date__c = Date.today()
        );
        insert tr;

        Compensation__c comp = new Compensation__c(
                Person__c = testContact.Id,
                Total__c = 100,
                Category__c = 'Tax',
                Description__c = 'TEST TEST',
                Date__c = Date.today()
        );
        insert comp;

        Loan__c loan = new Loan__c(
                Person__c = testContact.Id,
                Total__c = 100,
                Description__c = 'TEST TEST',
                Date__c = Date.today(),
                Bank_Account__c = bankAccount.Id,
                Billing_Person__c = testContact.Id
        );
        insert loan;
    }
}