force-app/main/default/objects/Account/fields/Account_Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Legal_Name__c</fullName>
    <label>Account Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Taxation__c.field-meta.xml
<CustomField>
    <fullName>Taxation__c</fullName>
    <label>Taxation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Poland Spolka</fullName>
            </value>
            <value>
                <fullName>Poland IB</fullName>
            </value>
            <value>
                <fullName>Belarus Company</fullName>
            </value>
            <value>
                <fullName>Belarus IB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used only for Propeller Plan account records</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation of the employee to the specific unit entity. Required to properly calculate unit-related spendings: e.g. office, salary taxes (if entered all in one record), accounting for the entity, etc.</description>
    <label>Unit</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Unit)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>PropellerPlan Team</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Person_to_Unit_Mapping_History__c/Person_to_Unit_Mapping_History__c.object-meta.xml
<CustomObject>
    <label>Person to Unit Mapping History</label>
    <nameField>
        <displayFormat>PUM-{000000}</displayFormat>
        <label>Person to Unit Mapping History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person to Unit Mapping History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person_to_Unit_Mapping_History__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Person to Unit Mapping History</relationshipLabel>
    <relationshipName>Person_to_Unit_Mapping_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PersonToUnitMapServiceTest.cls
/**
 * Created by kirillreutski on 24.03.24.
 */

@IsTest
private class PersonToUnitMapServiceTest {
    @IsTest
    static void testBehavior() {
        Account internalAccountRecord = new Account(
                Name = 'Propeller Plan',
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId(),
                Taxation__c = 'Poland IB'
        );
        insert internalAccountRecord;
        Contact internalContactRecord = new Contact(
                RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId(),
                LastName = 'Tester',
                Inactive__c = false,
                AccountId = internalAccountRecord.Id,
                Unit__c = internalAccountRecord.Id
        );

        insert internalContactRecord;
        Account internalLegalEntityPLRecord = new Account(
                Name = 'Propeller Plan PL',
                Account_Legal_Name__c = 'Propeller Plan Sp. z o.o.',
                RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId()
        );
        insert internalLegalEntityPLRecord;

        PersonToUnitMapService.createSnapshot(System.today().year(), null);
        System.assert([SELECT Id FROM Person_to_Unit_Mapping_History__c].size() > 0);
        System.assert(PersonToUnitMapService.getAccountId(internalContactRecord.Id, System.today().year(), System.today().month()) == internalAccountRecord.Id);
        System.assert(PersonToUnitMapService.getPersonsInUnit(internalAccountRecord.Id, System.today().year(), System.today().month()) == 1);
        System.assert(PersonToUnitMapService.getPersonsByUnit(System.today().year(), System.today().month()).size() > 0);
        System.assert(PersonToUnitMapService.personsAmount(System.today().year(), System.today().month()) > 0);
    }
}