force-app/main/default/objects/Account/fields/Account_Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Legal_Name__c</fullName>
    <label>Account Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Contact__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.ParentId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contractor__c.field-meta.xml
<CustomField>
    <fullName>Contractor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contractor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Contractor)</relationshipLabel>
    <relationshipName>Contracted_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used only for Propeller Plan account records</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Case/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>PropellerPlan Team</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INVC-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Owner__c.field-meta.xml
<CustomField>
    <fullName>Project_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timecard__c/Timecard__c.object-meta.xml
<CustomObject>
    <label>Timecard</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Timecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timecard__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Effort__c.field-meta.xml
<CustomField>
    <fullName>Effort__c</fullName>
    <label>Effort</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Invoice_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Line Item</label>
    <referenceTo>Invoice_Line_Item__c</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This contact is inactive.</errorMessage>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>Propeller Plan</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Case__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceGenerationSchedulerTest.cls
@IsTest
private class InvoiceGenerationSchedulerTest {
	@TestSetup
	static void setup() {
		Account internalAccountRecord = new Account(
				Name = 'Propeller Plan',
				RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId()
		);
		insert internalAccountRecord;
		Contact internalContactRecord = (Contact)pp_T.createSObject('Contact', new Map<String, Object>{ 'fields' => new List<String>{ 'FirstName', 'LastName' } });
		internalContactRecord.AccountId = internalAccountRecord.Id;
		internalContactRecord.Inactive__c = false;
		insert internalContactRecord;
		Account internalLegalEntityPLRecord = new Account(
				Name = 'Propeller Plan PL',
				Account_Legal_Name__c = 'Propeller Plan Sp. z o.o.',
				RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId()
		);
		insert internalLegalEntityPLRecord;
		Contact billingContact = (Contact)pp_T.createSObject('Contact', new Map<String, Object>{ 'fields' => new List<String>{ 'FirstName', 'LastName' } });
		billingContact.AccountId = internalLegalEntityPLRecord.Id;
		billingContact.Inactive__c = false;
		insert billingContact;
		Contact internalContactRecord2 = (Contact)pp_T.createSObject('Contact', new Map<String, Object>{ 'fields' => new List<String>{ 'FirstName', 'LastName' } });
		internalContactRecord2.AccountId = internalAccountRecord.Id;
		internalContactRecord2.Inactive__c = false;
		insert internalContactRecord2;
		Project__c internalProject = (Project__c)pp_T.createSObject('Project__c', new Map<String, Object>{ 'fields' => new List<String>{ 'Name' } });
		internalProject.Account__c = internalAccountRecord.Id;
		insert internalProject;
		Case internalCaseRecord = (Case)pp_T.createSObject('Case', new Map<String, Object>{ 'fields' => new List<String>{ 'Subject', 'Status' } });
		internalCaseRecord.Project__c = internalProject.Id;
		insert internalCaseRecord;
		Timecard__c internalTimecard = (Timecard__c)pp_T.createSObject('Timecard__c', new Map<String, Object>{ 'fields' => new List<String>{ 'Effort__c', 'Work_Date__c' } });
		internalTimecard.Person__c = internalContactRecord.Id;
		internalTimecard.Case__c = internalCaseRecord.Id;
		insert internalTimecard;

		Account accountRecord = (Account)pp_T.createSObject('Account', new Map<String, Object>{ 'fields' => new List<String>{ 'Name' } });
		insert accountRecord;
		Contact contactRecord = (Contact)pp_T.createSObject('Contact', new Map<String, Object>{ 'fields' => new List<String>{ 'FirstName', 'LastName' } });
		contactRecord.AccountId = accountRecord.Id;
		insert contactRecord;
		Project__c project = (Project__c)pp_T.createSObject('Project__c', new Map<String, Object>{ 'fields' => new List<String>{ 'Name', 'Rate__c' } });
		project.Account__c = accountRecord.Id;
		insert project;
		Case caseRecord = (Case)pp_T.createSObject('Case', new Map<String, Object>{ 'fields' => new List<String>{ 'Subject', 'Status' } });
		caseRecord.Project__c = project.Id;
		insert caseRecord;
		Timecard__c timecard = new Timecard__c(
				Person__c = internalContactRecord.Id,
				Case__c = caseRecord.Id,
				Effort__c = 1,
				Work_Date__c = Date.today().toStartOfMonth().addDays(-1)
		);
		insert timecard;

		Account accountRecord2 = (Account)pp_T.createSObject('Account', new Map<String, Object>{ 'fields' => new List<String>{ 'Name' } });
		insert accountRecord2;
		Contact contactRecord2 = (Contact)pp_T.createSObject('Contact', new Map<String, Object>{ 'fields' => new List<String>{ 'FirstName', 'LastName' } });
		contactRecord2.AccountId = accountRecord2.Id;
		insert contactRecord2;
		accountRecord2.Billing_Contact__c = contactRecord2.Id;
		accountRecord2.Contractor__c = billingContact.Id;
		update accountRecord2;
		Project__c project2 = (Project__c)pp_T.createSObject('Project__c', new Map<String, Object>{ 'fields' => new List<String>{ 'Name', 'Rate__c' } });
		project2.Account__c = accountRecord2.Id;
		project2.Project_Owner__c = internalContactRecord2.Id;
		insert project2;
		Case caseRecord2 = (Case)pp_T.createSObject('Case', new Map<String, Object>{ 'fields' => new List<String>{ 'Subject', 'Status' } });
		caseRecord2.Project__c = project2.Id;
		insert caseRecord2;
		Timecard__c timecard2 = new Timecard__c(
				Person__c = internalContactRecord2.Id,
				Case__c = caseRecord2.Id,
				Effort__c = 1,
				Work_Date__c = Date.today().toStartOfMonth().addDays(-1)
		);
		insert timecard2;
	}

	@IsTest
	static void scheduler_Should_NotGenerateInvoices_When_PrepareInvoices() {
		Test.startTest();
			InvoiceService.prepareInvoices();

		Test.stopTest();
		List<Invoice__c> invoices = new pp_Query('Invoice__c').selectAllFields().run();
		Map<Id, Invoice__c> invoiceMap = new Map<Id, Invoice__c>(invoices);
		InvoiceService.linkTimeCardsToInvoiceLineItems(invoiceMap.keySet());
		pp_T.expect(new pp_Query('Invoice__c').countQuery()).toEqual(2);
		pp_T.expect(new pp_Query('Invoice_Line_Item__c').countQuery()).toEqual(2);

		// dumb
		InvoiceService.generateInvoicesPDF(invoiceMap.keySet());
		InvoiceService.prepareMapping(invoices[0]);
	}

}