force-app/main/default/objects/Account/fields/Billing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country_Code__c</fullName>
    <label>Billing Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BY</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Compensation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compensation__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF (Closed__c, &apos;Closed&apos;, &apos;Open&apos;)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Workload__c.field-meta.xml
<CustomField>
    <fullName>Workload__c</fullName>
    <label>Workload</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Part-time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timecard__c/Timecard__c.object-meta.xml
<CustomObject>
    <label>Timecard</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Timecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timecard__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Effort__c.field-meta.xml
<CustomField>
    <fullName>Effort__c</fullName>
    <label>Effort</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This contact is inactive.</errorMessage>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>Propeller Plan</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacation__c/Vacation__c.object-meta.xml
<CustomObject>
    <label>Vacation</label>
    <nameField>
        <displayFormat>VAC-{000000}</displayFormat>
        <label>Vacation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vacations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vacation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vacations</relationshipLabel>
    <relationshipName>Vacations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Past</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Vacation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Vacation_End_Date__c</fullName>
    <label>Vacation End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Vacation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Start_Date__c</fullName>
    <label>Vacation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vacation__c/fields/Vacation_Type__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Type__c</fullName>
    <label>Vacation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day Off</fullName>
                <default>true</default>
                <label>Day Off</label>
            </value>
            <value>
                <fullName>Holiday Season</fullName>
            </value>
            <value>
                <fullName>Part Time</fullName>
            </value>
            <value>
                <fullName>Personal Vacation</fullName>
            </value>
            <value>
                <fullName>Sick Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CountingExtraHoursSchedulerTest.cls
/**
 * Created on 28.03.23.
 */

@IsTest
private class CountingExtraHoursSchedulerTest {

    @TestSetup
    static void setup() {
        Account account = new Account(Name = 'Propeller Plan', Billing_Country_Code__c = 'PL');
        insert account;

        Contact contact = new Contact(LastName = 'Test1', Inactive__c = false, AccountId = account.Id, Employer__c = account.Id);
        Contact contact2 = new Contact(LastName = 'Test2', Inactive__c = false, AccountId = account.Id);
        Contact contact3 = new Contact(LastName = 'Test3', Inactive__c = false, AccountId = account.Id, Workload__c = 'Part-time');
        insert new List<Contact> {contact, contact2, contact3};

        Vacation__c vac1 = new Vacation__c(
                Vacation_Start_Date__c = System.today().addMonths(-1).toStartOfMonth().addDays(2),
                Vacation_End_Date__c = System.today().addMonths(-1).toStartOfMonth().addDays(4),
                Vacation_Type__c = 'Personal Vacation',
                Status__c = 'Past',
                Employee__c = contact.Id
        );
        Vacation__c vac2 = new Vacation__c(
                Vacation_Start_Date__c = System.today().addMonths(-1).toStartOfMonth().addDays(5),
                Vacation_End_Date__c = System.today().addMonths(-1).toStartOfMonth().addDays(6),
                Vacation_Type__c = 'Holiday Season',
                Status__c = 'Past',
                Employee__c = contact.Id
        );
        Vacation__c vac3 = new Vacation__c(
                Vacation_Start_Date__c = System.today().addMonths(-1).toStartOfMonth().addDays(8),
                Vacation_End_Date__c = System.today().addMonths(-1).toStartOfMonth().addDays(8),
                Vacation_Type__c = 'Personal Vacation',
                Status__c = 'Planned',
                Employee__c = contact.Id
        );
        Vacation__c vac4 = new Vacation__c(
                Vacation_Start_Date__c = System.today().addMonths(-1).toStartOfMonth().addDays(10),
                Vacation_End_Date__c = System.today().addMonths(-1).toStartOfMonth().addDays(11),
                Vacation_Type__c = 'Personal Vacation',
                Status__c = 'Past',
                Employee__c = contact.Id
        );
        insert new List<Vacation__c> {vac1, vac2, vac3, vac4};

        Case testCase = new Case();
        insert testCase;

        Timecard__c timecard = new Timecard__c(Person__c = contact.Id, Effort__c = 180, Work_Date__c = System.today().addMonths(-1).toStartOfMonth(), Case__c = testCase.Id);
        Timecard__c timecard2 = new Timecard__c(Person__c = contact2.Id, Effort__c = 250, Work_Date__c = System.today().addMonths(-1).toStartOfMonth().addDays(1), Case__c = testCase.Id);
        Timecard__c timecard3 = new Timecard__c(Person__c = contact2.Id, Effort__c = 400, Work_Date__c = System.today().addMonths(-1).toStartOfMonth().addDays(2), Case__c = testCase.Id);
        Timecard__c timecard4 = new Timecard__c(Person__c = contact2.Id, Effort__c = 60, Work_Date__c = System.today().addMonths(-1).toStartOfMonth(), Case__c = testCase.Id);
        Timecard__c timecard5 = new Timecard__c(Person__c = contact3.Id, Effort__c = 120, Work_Date__c = System.today().addMonths(-1).toStartOfMonth(), Case__c = testCase.Id);
        insert new List<Timecard__c> {timecard, timecard2, timecard3, timecard4, timecard5};
    }

    @IsTest
    static void testCountingExtraHours() {
        new CountingExtraHoursScheduler().execute(null);
//        pp_T.expect(new pp_Query('Compensation__c').countQuery()).toBe(3);
    }
}