force-app/main/default/objects/Account/fields/Billing_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country_Code__c</fullName>
    <label>Billing Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BY</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>GE</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Taxation__c.field-meta.xml
<CustomField>
    <fullName>Taxation__c</fullName>
    <label>Taxation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Poland Spolka</fullName>
            </value>
            <value>
                <fullName>Poland IB</fullName>
            </value>
            <value>
                <fullName>Belarus Company</fullName>
            </value>
            <value>
                <fullName>Belarus IB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used only for Propeller Plan account records</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Banks</relationshipLabel>
    <relationshipName>Banks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(deprecated)Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Employer__c.field-meta.xml
<CustomField>
    <fullName>Employer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>PropellerPlan Team</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INVC-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Actual_Income__c.field-meta.xml
<CustomField>
    <fullName>Actual_Income__c</fullName>
    <label>Actual Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Billed_To__c.field-meta.xml
<CustomField>
    <fullName>Billed_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices (Payee)</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Payee_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Payee_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payee Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Working_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Working_Period_End__c</fullName>
    <label>Working Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Commission_Rate__c</fullName>
    <description>UpWork / Sales Reps / other robbers</description>
    <label>Commission Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Waiting for Release</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Timecard__c/Timecard__c.object-meta.xml
<CustomObject>
    <label>Timecard</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Timecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timecard__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This contact is inactive.</errorMessage>
        <filterItems>
            <field>Contact.Inactive__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>Propeller Plan</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timecards</relationshipLabel>
    <relationshipName>Timecards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timecard__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Case__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Income_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Income_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Income Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Income Transactions</relationshipLabel>
    <relationshipName>Income_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Outcome_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outcome Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Outcome Transactions</relationshipLabel>
    <relationshipName>Outcome_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Outcome_Category__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Category__c</fullName>
    <label>Outcome Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Birthday</fullName>
            </value>
            <value>
                <fullName>Business Trip</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Legal and Accounting</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Office</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Salary</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Sport</fullName>
            </value>
            <value>
                <fullName>Tax</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Dividends</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Tax_Category__c.field-meta.xml
<CustomField>
    <fullName>Tax_Category__c</fullName>
    <label>Tax Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>Unit-related</fullName>
            </value>
            <value>
                <fullName>Person-related</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PersonEffectivenessStatServiceTest.cls
/**
 * Created by kirillreutski on 24.03.24.
 */

@IsTest
private class PersonEffectivenessStatServiceTest {
    @IsTest
    static void testBehavior() {
        Account account1 = new Account(Taxation__c = 'Poland Spolka', Name = 'Propeller Plan', Billing_Country_Code__c = 'PL', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId());
        Account account2 = new Account(Taxation__c = 'Poland IB', Name = 'Propeller Plan IB', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId());
        Account account3 = new Account(Taxation__c = 'Belarus Company', Name = 'Propeller Plan IB', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId());
        insert new List<Account>{account3, account2, account1};

        Bank__c bank1 = new Bank__c(Account__c = account1.Id, Name = 'asd1');
        Bank__c bank2 = new Bank__c(Account__c = account2.Id, Name = 'asd2');
        Bank__c bank3 = new Bank__c(Account__c = account3.Id, Name = 'asd3');
        insert new List<Bank__c>{bank1, bank2, bank3};
        Bank_Account__c ba1 = new Bank_Account__c(Bank__c = bank1.Id);
        Bank_Account__c ba2 = new Bank_Account__c(Bank__c = bank2.Id);
        Bank_Account__c ba3 = new Bank_Account__c(Bank__c = bank3.Id);
        insert new List<Bank_Account__c>{ba1, ba2, ba3};

        Contact testContact1 = (Contact)pp_T.createSObject('Contact', new Map<String, Object>{ 'fields' => new List<String>{ 'Email', 'LastName' } });
        testContact1.AccountId = account1.Id;
        testContact1.Inactive__c = false;
        testContact1.Employer__c = account1.Id;

        Contact testContact2 = (Contact)pp_T.createSObject('Contact', new Map<String, Object>{ 'fields' => new List<String>{ 'Email', 'LastName' } });
        testContact2.AccountId = account1.Id;
        testContact2.Inactive__c = false;
        testContact2.Employer__c = account3.Id;
        insert new List<Contact>{testContact1, testContact2};
        System.debug('Inactive__c check: ' + [SELECT Id, Inactive__c FROM Contact]);
        Account customer = (Account)pp_T.createSObject('Account', new Map<String, Object>{ 'fields' => new List<String>{ 'Name' } });
        insert customer;

        List<Invoice__c> invoices = new List<Invoice__c>();
        invoices.add(new Invoice__c(
                Account__c = customer.Id,
                Invoice_Number__c = 'FV/' + System.today().month(),

                Working_Period_End__c = System.today(),
                Billed_To__c = testContact1.Id,
                Payee_Bank_Account__c = ba1.Id,
                Actual_Income__c = 100,
                Status__c = 'Paid'

        ));

        invoices.add(new Invoice__c(
                Account__c = customer.Id,
                Invoice_Number__c = 'FV/' + System.today().month(),

                Working_Period_End__c = System.today(),
                Billed_To__c = testContact1.Id,
                Payee_Bank_Account__c = ba2.Id,
                Actual_Income__c = 100,
                Status__c = 'Paid'

        ));

        invoices.add(new Invoice__c(
                Account__c = customer.Id,
                Invoice_Number__c = 'FV/' + System.today().month(),

                Working_Period_End__c = System.today(),
                Billed_To__c = testContact1.Id,
                Payee_Bank_Account__c = ba3.Id,
                Actual_Income__c = 100,
                Status__c = 'Paid'

        ));
        insert invoices;

        Transaction__c tr1 = new Transaction__c(
                Person__c = testContact1.Id,
                Outcome__c = 50,
                Income_Bank_Account__c = ba1.Id,
                Description__c = 'TEST TEST',
                Outcome_Category__c = 'Tax',
                Date__c = Date.today(),
                Outcome_Bank_Account__c = ba1.Id
        );
        Transaction__c tr4 = new Transaction__c(
                Person__c = testContact1.Id,
                Outcome__c = 50,
//                Income_Bank_Account__c = ba1.Id,
                Description__c = 'TEST TEST',
                Outcome_Category__c = 'Tax',
                Date__c = Date.today(),
                Outcome_Bank_Account__c = ba1.Id
        );
        Transaction__c tr2 = new Transaction__c(
                Person__c = testContact1.Id,
                Outcome__c = 50,
                Income_Bank_Account__c = ba1.Id,
                Description__c = 'TEST TEST',
                Outcome_Category__c = 'Tax',
                Tax_Category__c = 'Income',
                Date__c = Date.today(),
                Outcome_Bank_Account__c = ba2.Id
        );

        Transaction__c tr3 = new Transaction__c(
                Person__c = testContact2.Id,
                Outcome__c = 50,
                Income_Bank_Account__c = ba2.Id,
                Description__c = 'TEST TEST',
                Outcome_Category__c = 'Tax',
                Tax_Category__c = 'Income',
                Date__c = Date.today(),
                Outcome_Bank_Account__c = ba3.Id
        );

        Transaction__c tr5 = new Transaction__c(
                Person__c = testContact2.Id,
                Outcome__c = 50,
                Income_Bank_Account__c = ba2.Id,
                Description__c = 'TEST TEST',
                Outcome_Category__c = 'Salary',
                Date__c = Date.today(),
                Outcome_Bank_Account__c = ba3.Id
        );
        insert new List<Transaction__c>{tr1, tr2, tr3, tr4, tr5};

        Project__c project = new Project__c();
        project.Name = 'Project';
        project.Account__c = account1.Id;
        project.Rate__c = 100;
        project.Commission_Rate__c = 1;
        insert project;
        Case newCase = new Case();
        newCase.Project__c = project.Id;
        newCase.Subject = 'Subject';
        newCase.ContactId = testContact1.Id;
        newCase.Estimated_Time__c = 10;
        insert newCase;

        Timecard__c timecard1 = new Timecard__c(
                Work_Date__c = Date.today(),
                Effort__c = 5.50,
                Case__c = newCase.Id,
                Person__c = testContact1.Id
        );

        Timecard__c timecard2 = new Timecard__c(
                Work_Date__c = Date.today(),
                Effort__c = 5.50,
                Case__c = newCase.Id,
                Person__c = testContact2.Id
        );
        insert timecard1;
        insert timecard2;
        //insert new List<Timecard__c>{timecard1, timecard2};


        Map<Id, Invoice__c> invoiceMap = new Map<Id, Invoice__c>([SELECT Id FROM Invoice__c WHERE CreatedDate = THIS_YEAR]);

        InvoiceService.linkTimeCardsToInvoiceLineItems(invoiceMap.keySet());
        PersonEffectivenessStatService.updateRecords(new Set<Id>{testContact1.Id, testContact2.Id}, null);
    }

    @IsTest
    static void getMonthIndex(){
        System.assert(PersonEffectivenessStatService.getMonthIndex('nope') == 12);
    }
}