force-app/main/default/objects/PPRS_SObject_Setting__mdt/PPRS_SObject_Setting__mdt.object-meta.xml
<CustomObject>
    <label>PPRS SObject Setting</label>
    <pluralLabel>PPRS SObject Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/PPRS_SObject_Setting__mdt/fields/Schedulable__c.field-meta.xml
<CustomField>
    <fullName>Schedulable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Schedulable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PPRS_SObject_Setting__mdt/fields/Schedulable_Day__c.field-meta.xml
<CustomField>
    <fullName>Schedulable_Day__c</fullName>
    <label>Schedulable Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PPRS_SObject_Setting__mdt/fields/Schedulable_Period__c.field-meta.xml
<CustomField>
    <fullName>Schedulable_Period__c</fullName>
    <label>Schedulable Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>daily</fullName>
                <default>true</default>
                <label>daily</label>
            </value>
            <value>
                <fullName>weekly</fullName>
            </value>
            <value>
                <fullName>monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PPRSSchedule.cls
/**
 * Created by kirillreutski on 3.09.24.
 */

public without sharing class PPRSSchedule implements Schedulable {
    public void execute(SchedulableContext param1) {
        // get scheduled settings
        List<PPRS_SObject_Setting__mdt> settingsToHandle = getSettingsToHandle();

        throw new PPRSException('Not implemented yet');
    }

    public static List<PPRS_SObject_Setting__mdt> getSettingsToHandle() {
        String currentDayOfWeekS = Datetime.now().format('u');
        Integer currentDayOfWeek = Integer.valueOf(currentDayOfWeekS);
        Integer currentDayOfMonth = Datetime.now().day();
        List<PPRS_SObject_Setting__mdt> settingsToHandle = new List<PPRS_SObject_Setting__mdt>();

        for (PPRS_SObject_Setting__mdt setting : PPRSSettings.settingsMdt) {
            if (setting.Schedulable__c) {
                if (setting.Schedulable_Period__c == 'daily') settingsToHandle.add(setting);
                else if (setting.Schedulable_Period__c == 'monthly') {
                    if (currentDayOfMonth == setting.Schedulable_Day__c) settingsToHandle.add(setting);
                }
                else if (setting.Schedulable_Period__c == 'weekly') {
                    if (currentDayOfWeek == setting.Schedulable_Day__c) settingsToHandle.add(setting);
                }
            }
        }

        return settingsToHandle;
    }
}