force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(deprecated)Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INVC-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Billed_By__c.field-meta.xml
<CustomField>
    <fullName>Billed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices (Payer)</relationshipLabel>
    <relationshipName>Billed_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Billed_To__c.field-meta.xml
<CustomField>
    <fullName>Billed_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices (Payee)</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Payee_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Payee_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payee Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Working_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Working_Period_End__c</fullName>
    <label>Working Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/InvoiceGenerationScheduler.cls
public class InvoiceGenerationScheduler implements Schedulable, Database.Batchable<SObject>, Database.AllowsCallouts {
	private Set<Id> invoiceIds;

	public InvoiceGenerationScheduler(Set<Id> invoiceIds) {
		this.invoiceIds = invoiceIds;
	}

	public void execute(System.SchedulableContext context) {
		InvoiceService.prepareInvoices();
	}

	public Database.QueryLocator start(Database.BatchableContext bc) {
		return Database.getQueryLocator(new pp_Query('Invoice__c')
				.selectAllFields()
				.selectAllFields('Account__r')
				.selectAllFields('Billed_To__r')
				.selectAllFields('Billed_By__r')
				.selectAllFields('Payee_Bank_Account__r')
				.selectAllFields('Payee_Bank_Account__r.Bank__r')
				.selectAllFields('Payee_Bank_Account__r.Bank__r.Account__r')
				.addSubquery(
						pp_Query.subquery('Invoice_Line_Items__r')
								.selectAllFields()
				)
				.byId(invoiceIds)
				.toQueryString()
				.replace(' billed_to__r.individualid,', '').replace(' billed_by__r.individualid,', '')					// Workaround for individualid
				.replace(' billed_to__r.pronouns,', '').replace(' billed_by__r.pronouns,', '')							// Workaround for pronouns
				.replace(' billed_to__r.genderidentity,', '').replace(' billed_by__r.genderidentity,', '')				// Workaround for genderidentity
				.replace(' billed_to__r.ispriorityrecord,', '').replace(' billed_by__r.ispriorityrecord,', '')			// Workaround for ispriorityrecord
				.replace(' account__r.tier,', '').replace(' payee_bank_account__r.bank__r.account__r.tier,', ''));		// Workaround for tier
	}

	public void execute(Database.BatchableContext BC, List<SObject> scope) {
		Map<Id, ContentVersion> contentVersionByInvoice = new Map<Id, ContentVersion>();

		for (Invoice__c inv: (List<Invoice__c>) scope) {
			try {
				if (!Test.isRunningTest()) PDFMonkeyConnector.ResponseDocument result = PDFMonkeyConnector.createDocument('8E339346-F647-4FE3-A986-7FAD1BD71F37', inv.Invoice_Number__c.replaceAll('/', '_') + '.pdf', inv.Id, InvoiceService.prepareMapping(inv));
			} catch (pp_RestExplorer.ErrorResponseException ex) {
				pp_R.debug.run(ex.getMessage());
			}

			if (String.isEmpty(inv.Account__r.Monthly_Report_ID__c)) continue;

			Blob invoiceReport = null;
			ContentVersion contentVersionRecord = new ContentVersion();
			if (Test.isRunningTest()) {
				invoiceReport = Blob.valueOf('0');
			} else {
				invoiceReport = new pp_SalesforceRestExplorer('analytics/reports/' + inv.Account__r.Monthly_Report_ID__c)
						.doGet()
						.setHeader('Accept', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
						.getBlobResult();
			}
			contentVersionRecord.Title = inv.Account__r.Name + ' - Propeller Plan - ' + new pp_Moment(inv.Working_Period_End__c).format('MMyyyy');
			if (invoiceReport != null) {
				contentVersionRecord.VersionData = invoiceReport;
				contentVersionRecord.PathOnClient = '/' + contentVersionRecord.Title + '.xlsx';
				contentVersionRecord.IsMajorVersion = true;
				contentVersionByInvoice.put(inv.Id, contentVersionRecord);
			}
		}
		insert contentVersionByInvoice.values();
		Map<Id, ContentVersion> selectedContentVersions = new Map<Id, ContentVersion>(
				(List<ContentVersion>)new pp_Query('ContentVersion')
						.selectFields(new Set<String>{'Id', 'ContentDocumentId'})
						.byId(new Map<Id, ContentVersion>(contentVersionByInvoice.values()).keySet())
						.run()
		);

		List<ContentDocumentLink> contentDocumentLinks = new List<ContentDocumentLink>();
		for (Id invoiceId: contentVersionByInvoice.keySet()) {
			if (!selectedContentVersions.containsKey(contentVersionByInvoice.get(invoiceId).Id)) {
				continue;
			}
			ContentVersion contentVersionRecord = selectedContentVersions.get(contentVersionByInvoice.get(invoiceId).Id);
			ContentDocumentLink contentDocumentLinkRecord = new ContentDocumentLink();
			contentDocumentLinkRecord.LinkedEntityId = invoiceId;
			contentDocumentLinkRecord.ShareType = 'V';
			contentDocumentLinkRecord.ContentDocumentId = contentVersionRecord.ContentDocumentId;
			contentDocumentLinks.add(contentDocumentLinkRecord);
		}
		insert contentDocumentLinks;
	}

	public void finish(Database.BatchableContext BC) {
	}
}