force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Banks</relationshipLabel>
    <relationshipName>Banks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(deprecated)Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INVC-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Actual_Income__c.field-meta.xml
<CustomField>
    <fullName>Actual_Income__c</fullName>
    <label>Actual Income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Billed_To__c.field-meta.xml
<CustomField>
    <fullName>Billed_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoices (Payee)</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Payee_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Payee_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payee Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Working_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Working_Period_End__c</fullName>
    <label>Working Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceTest.cls
@IsTest
private class InvoiceTest {
    @IsTest
    static void invoiceTest() {
        Contact testContact = (Contact)pp_T.createSObject('Contact', new Map<String, Object>{ 'fields' => new List<String>{ 'Email', 'LastName' } });
        insert testContact;
        Account customer = (Account)pp_T.createSObject('Account', new Map<String, Object>{ 'fields' => new List<String>{ 'Name' } });
        insert customer;

        Bank__c testBank = (Bank__c)pp_T.createSObject('Bank__c', new Map<String, Object>{ 'fields' => new List<String>{ 'Name' } });
        insert testBank;
        Bank_Account__c testBAcc = new Bank_Account__c(Bank__c = testBank.Id);
        insert testBAcc;
        List<Invoice__c> invoices = new List<Invoice__c>();
        invoices.add(new Invoice__c());
        invoices.add(new Invoice__c(
                Account__c = customer.Id,
                Invoice_Number__c = 'test',
                Working_Period_End__c = System.today(),
        	    Billed_To__c = testContact.Id,
                Payee_Bank_Account__c = testBAcc.Id,
        	    Actual_Income__c = 100
        ));
        insert invoices;

        pp_T.expect(new pp_Query('Invoice__c').countQuery()).toEqual(2);
        List<Transaction__c> txList = new pp_Query('Transaction__c')
                .selectField('Income__c')
                .selectField('Description__c')
                .addConditionEq('Invoice__c', invoices[1].Id)
                .run();
        pp_T.expect(txList.size()).toEqual(1);
        pp_T.expect(txList[0].Income__c).toEqual(100);

        invoices[1].Actual_Income__c = 50;
        update invoices[1];
        txList = new pp_Query('Transaction__c')
                .selectField('Income__c')
                .addConditionEq('Invoice__c', invoices[1].Id)
                .run();
        pp_T.expect(txList.size()).toEqual(1);
        pp_T.expect(txList[0].Income__c).toEqual(50);

        delete invoices[1];
        pp_T.expect(new pp_Query('Transaction__c')
                .addConditionEq('Invoice__c', invoices[1].Id)
                .countQuery()).toEqual(0);
    }
}